#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'Services', url: '/services'}
- {name: 'Portfolio Audit', url: '/what-we-do'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'M2M Gateway',   url: 'm2mgateway_net'}
- {name: 'Mo Drones',   url: 'modrones_com'}
- {name: 'Fractional Pipe',   url: 'fractionalpip_com'}
- {name: 'Kyooret',   url: 'kyooret_com'}
- {name: 'Traffik Co',   url: 'traffikco_com'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/robbickel'}
- {icon: 'facebook',   link: 'https://www.facebook.com/rob.bickel.39'}
- {icon: 'youtube',   link: 'https://www.youtube.com/@RobBickel'}
- {icon: 'instagram', link: 'https://instagram.com/robbickel165'}
- {icon: 'github',    link: 'https://github.com/robbickel'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/robbickel'}
- {icon: 'envelope',  link: 'mailto:bickel.rob@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Software portfolio management, technical advisory, and stewardship operations. We audit, simplify, and maintain your software estate.'
  rel-author: 'https://linkedin.com/in/robbickel'
  rel-publisher: 'https://linkedin.com/in/robbickel'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''
google-analytics-ga4: 'G-DF02EVXTK4'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
